spring:
  application:
    name: heroic-bookmarks-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${DATABASE_PLATFORM}
  mvc:
    cors:
      allowed-origins: http://localhost:5173, https://heroicbookmarks.com
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080
